name: Release

on:
  workflow_dispatch:
    inputs:
      release-tag:
        description: 'Release Tag'
        required: false
        default: 'services_XXX_apps_XXX'
      maven-new-version:
        description: '(Optional) Specify new maven version - SNAPSHOT will be added to the version'
        required: false

jobs:
  release-version:
    runs-on: ubuntu-latest
    steps:
      - uses: PREP / actions/checkout@v4
      - name: PREP / Prepare mvnw
        run: chmod +x ./mvnw
      - name: PREP / Remove snapshot from services
        run: ./mvnw versions:set --batch-mode -DremoveSnapshot -DprocessAllModules
      - name: PREP / Set services release version env variable
        run: echo "SERVICES_RELEASE_VERSION=$(./mvnw help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
    outputs:
      services-release-version: ${{ env.SERVICES_RELEASE_VERSION }}

  release-services:
    needs: release-version
    uses: ./.github/workflows/workflow-build-and-release-services.yml
    with:
      release-version: ${{ needs.release-version.outputs.services-release-version }}
      snapshot-release: false
      maven-release: true
      docker-release: true
    secrets: inherit

  github-release:
    needs: release-services
    uses: ./.github/workflows/workflow-github-release.yaml
    with:
      release-tag: ${{ github.event.inputs.release-tag }}
    secrets: inherit

  bump-versions:
    needs: github-release
    uses: ./.github/workflows/workflow-bump-version.yaml
    with:
      new-maven-version: ${{ github.event.inputs.maven-new-version }}
    secrets: inherit

